analyzer:
  enabled_package_managers:
    - Maven
  
  disabled_package_managers:
    - Bazel
    - Bower
    - Bundler
    - Cargo
    - Carthage
    - CocoaPods
    - Composer
    - Conan
    - DotNet
    - GoMod
    - Gradle
    - GradleInspector
    - NPM
    - NuGet
    - PIP
    - Pipenv
    - PNPM
    - Poetry
    - Pub
    - SBT
    - SPM
    - Stack
    - Yarn
    - Yarn2
  
  skip_excluded: true
  allow_dynamic_versions: false
